// Automatically generated by MockGen. DO NOT EDIT!
// Source: users/users.go

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of UserInterface interface
type MockUserInterface struct {
	ctrl     *gomock.Controller
	recorder *_MockUserInterfaceRecorder
}

// Recorder for MockUserInterface (not exported)
type _MockUserInterfaceRecorder struct {
	mock *MockUserInterface
}

func NewMockUserInterface(ctrl *gomock.Controller) *MockUserInterface {
	mock := &MockUserInterface{ctrl: ctrl}
	mock.recorder = &_MockUserInterfaceRecorder{mock}
	return mock
}

func (_m *MockUserInterface) EXPECT() *_MockUserInterfaceRecorder {
	return _m.recorder
}

func (_m *MockUserInterface) GetName() string {
	ret := _m.ctrl.Call(_m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockUserInterfaceRecorder) GetName() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetName")
}

func (_m *MockUserInterface) SetName(_param0 string) {
	_m.ctrl.Call(_m, "SetName", _param0)
}

func (_mr *_MockUserInterfaceRecorder) SetName(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetName", arg0)
}
